name: Docker Build and Push

on:
  push:
    branches: ["**"]
  workflow_dispatch:

env:
  IMAGE_NAME: cubbieblue16/comet

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-common.yml
    with:
      tags: |
        type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
        type=ref,event=branch
        type=sha,prefix=sha-
      build-args: |
        COMET_BRANCH=${{ github.ref_name }}
